### ISSUE TITLE
As a user, I want to create a new todo item so that I can keep track of tasks I need to complete

### ISSUE THREAD

**Issue by henno** [henno/todo-app#2]
- [x] Input field is available to enter todo title
- [x] "Add" button creates the new todo
- [x] New todos appear at the top of the list
- [x] Empty todos cannot be created
- [x] User receives visual feedback when todo is created

**Comment by henno** [comment]
<img width="726" alt="Screenshot 2024-12-15 at 23 01 22" src="https://github.com/user-attachments/assets/78d29913-d667-41be-91a0-4520f92a7c13" />
